### PR TITLE
Replace the Prisma GraphQL extension with Apollo’s

### PR DESCRIPTION
**Pull request by alloy**
The required fix for the extension has been merged, so just waiting for a new release now. https://github.com/apollographql/apollo-tooling/pull/769

### CODE REVIEW

**Comment by orta** [comment]
Yep, I wonder if this will install it for folks - will make a release when I get into the office

**Comment by alloy** [comment]
I doubt it will uninstall. Might be a good idea to send a @-here in the channel that people should uninstall the other 2.

**Comment by orta** [comment]
Per-repo we can define "unwanted" we might be able to do that here

**Comment by jbaxleyiii** [comment]
@alloy @orta wanted to let you know that the new extension is being verified on the store right now! Please let us know if it works well for you and any features you'd like to see. I'd love to see it working in a Relay app at some point 😄 and see if the rest of the platform like the schema reg would be valuable for Artsy!

**Comment by alloy** [comment]
@jbaxleyiii Thanks! Everything seems to work well thus far (you can try it with [this](https://github.com/artsy/reaction) repo) 👍

The only thing that’s not working well right now is in operation variables validation. Relay Modern has [the `@argumentDefinition` directive](https://facebook.github.io/relay/docs/en/fragment-container.html#argumentdefinitions), which defines ‘local’ variables. These don’t need to be declared at the root of the operation, which currently leads to the many false positives seen below. It would be nice to either have that work or be able to disable that validation rule:

screen shot 2018-12-01 at 00 29 47

**Comment by jbaxleyiii** [comment]
Okay great! I’m going to try and play around with this tonight / this weekend. Im particularly interested in making sure operation extraction (and by extension validation) works for all kinds of clients!

I’ve been thinking through adding custom validation rules as part of the config as well for more advanced cases. Thanks for the playground repo 😍

**Pull request merged**
